export const casinoCards = [
  {
    logoSrc: './img/cards/card1/logo.jpg',
    alt: 'Midas logo',
    rating: '4.8',
    thirdColumnBottom: 'Midas Testebricht',
    fourColumnLeftTop: 'Regulation',
    fourColumnImgSrc: './img/cards/card1/pic.svg',
    fourColumnRightText: '260% bis zu 2600€ + 260 FS',
  },
  {
    logoSrc: './img/cards/card2/logo.jpg',
    alt: 'Mobilebet',
    rating: '4.9',
    thirdColumnBottom: 'Mobile Bet Testebricht',
    fourColumnLeftTop: 'Zalung Speed',
    fourColumnImgSrc: './img/cards/card2/pic.svg',
    fourColumnRightText: '100% von bis zu 100€ + 100fs',
  },
  {
    logoSrc: './img/cards/card3/logo.jpg',
    alt: 'Moi casino',
    rating: '5.0',
    thirdColumnBottom: 'Moi Casino Testebricht',
    fourColumnLeftTop: 'Regulation',
    fourColumnImgSrc: './img/cards/card3/pic.svg',
    fourColumnRightText: '300% bis zu 1000 € + 300 FS',
  },
  {
    logoSrc: './img/cards/card4/logo.jpg',
    alt: 'Mr Bet',
    rating: '4.7',
    thirdColumnBottom: 'Mr. Bet Testebricht',
    fourColumnLeftTop: 'Zalung Speed',
    fourColumnImgSrc: './img/cards/card4/pic.svg',
    fourColumnRightText: '100% von bis zu 100€ + 100fs',
  },
  {
    logoSrc: './img/cards/card1/logo.jpg',
    alt: 'Midas logo',
    rating: '4.8',
    fourColumnLeftTop: 'Regulation',
    fourColumnImgSrc: './img/cards/card1/pic.svg',
    fourColumnRightText: '260% bis zu 2600€ + 260 FS',
  },
  {
    logoSrc: './img/cards/card1/logo.jpg',
    alt: 'Midas logo',
    rating: '4.8',
    fourColumnLeftTop: 'Regulation',
    fourColumnImgSrc: './img/cards/card1/pic.svg',
    fourColumnRightText: '260% bis zu 2600€ + 260 FS',
  },
  {
    logoSrc: './img/cards/card1/logo.jpg',
    alt: 'Midas logo',
    rating: '4.8',
    fourColumnLeftTop: 'Regulation',
    fourColumnImgSrc: './img/cards/card1/pic.svg',
    fourColumnRightText: '260% bis zu 2600€ + 260 FS',
  },
  {
    logoSrc: './img/cards/card1/logo.jpg',
    alt: 'Midas logo',
    rating: '4.8',
    fourColumnLeftTop: 'Regulation',
    fourColumnImgSrc: './img/cards/card1/pic.svg',
    fourColumnRightText: '260% bis zu 2600€ + 260 FS',
  },
  {
    logoSrc: './img/cards/card1/logo.jpg',
    alt: 'Midas logo',
    rating: '4.8',
    fourColumnLeftTop: 'Regulation',
    fourColumnImgSrc: './img/cards/card1/pic.svg',
    fourColumnRightText: '260% bis zu 2600€ + 260 FS',
  },
];

export const filters = ['Slots', 'A1', 'MGA'];
